ansible_user: student
ansible_password: Passw0rd!
ansible_become: true
ansible_become_method: sudo
ansible_become_user: root
ansible_become_password: Passw0rd!
ansible_connection: ssh
ansible_shell_type: sh
ansible_shell_executable: /bin/bash
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
