ansible_user: "{{ windows_vars.ansible_user }}"
ansible_password: "{{ windows_vars.ansible_password }}"
ansible_connection: winrm
ansible_port: 5986
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore
