- name: Install Geany on Linux and Windows
  hosts: automation_targets
  gather_facts: yes
  vars_files:
    - vault_vars.yml

  tasks:
    - name: Install Geany on Debian/Ubuntu Linux
      when: ansible_os_family == "Debian"
      become: true
      apt:
        name: geany
        state: present
        update_cache: yes

    - name: Ensure Chocolatey is installed on Windows
      when: ansible_os_family == "Windows"
      win_shell: |
        if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'));
        }

    - name: Install Geany on Windows using Chocolatey
      when: ansible_os_family == "Windows"
      win_chocolatey:
        name: geany
        state: present
