- name: Install Geany on Linux and Windows
  hosts: automation_targets
  gather_facts: yes

  tasks:
    - name: Install Geany on Debian/Ubuntu Linux
      when: ansible_os_family == "Debian"
      become: true
      apt:
        name: geany
        state: present
        update_cache: yes
        
    - name: Uninstall Chocolatey
      when: ansible_os_family == "Windows"
      win_chocolatey:
        name: chocolatey
        state: absent

    - name: Check if Chocolatey is installed
      when: ansible_os_family == "Windows"
      win_command: choco -v
      register: choco_check
      ignore_errors: yes

    - name: Install Chocolatey if not present
      when: ansible_os_family == "Windows" and choco_check.rc != 0
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Geany on Windows using Chocolatey
      when: ansible_os_family == "Windows"
      win_chocolatey:
        name: geany
        state: present
