- name: Configure Cisco Devices with Banner
  hosts: all
  gather_facts: no
  tasks:
    - name: Set incoming banner
      ios_banner:
        banner: incoming
        text: |
          Welcome to {{ inventory_hostname }} Your home on the web!
        state: present
